#!/bin/bash
echo "[ LOCAL/USR - SHARE - KSYSGUARD - SYSTEMLOAD ]"
rm -f /home/replaceWithUserName/.local/share/ksysguard/SystemLoad2.sgrd
sudo touch /usr/share/ksysguard/SystemLoad2.sgrd
sudo bash -c 'cat << EOT > /usr/share/ksysguard/SystemLoad2.sgrd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE KSysGuardWorkSheet>
<WorkSheet rows="3" columns="2" locked="1" title="System Load" interval="0.5">
 <host name="localhost" shell="" port="-1" command="ksysguardd"/>
 <display hScale="6" column="0" row="0" showUnit="0" manualRange="0" vDistance="30" title="CPU History" rowSpan="1" svgBackground="" version="1" hLines="1" columnSpan="2" unit="" fontSize="8" class="FancyPlotter" labels="1" stacked="0" vLines="0" autoRange="1" vScroll="0">
  <beam sensorType="float" hostName="localhost" regexpSensorName="cpu/cpu.*/TotalLoad" color="0xffff8000,0xffe20800" />
 </display>
 <display title="Memory and Swap History" svgBackground="widgets/plot-background" hScale="6" column="0" row="1" showUnit="0" manualRange="0" vDistance="30" rowSpan="1" svgBackground="" version="1" hLines="1" columnSpan="1" unit="" fontSize="8" class="FancyPlotter" labels="1" stacked="0" vLines="0" autoRange="1" vScroll="0">
  <beam summationName="Memory" sensorName="mem/physical/application" sensorType="integer" hostName="localhost" color="0xffc000c0" />
  <beam summationName="Swap" sensorName="mem/swap/used" sensorType="integer" hostName="localhost" color="0xff00c000" />
 </display>
 <display title="Network History" svgBackground="widgets/plot-background" hScale="6" column="1" row="1" showUnit="0" manualRange="0" vDistance="30" rowSpan="1" svgBackground="" version="1" hLines="1" columnSpan="1" unit="" fontSize="8" class="FancyPlotter" labels="1" stacked="0" vLines="0" autoRange="1" vScroll="0">
  <beam sensorType="float" hostName="localhost" summationName="Receiving" regexpSensorName="network/interfaces/(?!lo|bridge|usbus|bond).*/receiver/data" color="0xB3A52D" />
  <beam sensorType="float" hostName="localhost" summationName="Sending" regexpSensorName="network/interfaces/(?!lo|bridge|usbus|bond).*/transmitter/data" color="0x844798" />
 </display>
 <display hScale="6" column="0" row="2" showUnit="0" manualRange="0" vDistance="30" title="Core Temperatures" rowSpan="1" svgBackground="" version="1" hLines="1" columnSpan="1" unit="" fontSize="8" class="FancyPlotter" labels="1" stacked="0" vLines="0" autoRange="1" vScroll="0">
  <beam sensorType="float" color="0xff0057ae,0xffe20800,0xfff3c300,0xffff0000" hostName="localhost" regexpSensorName="lmsensors/coretemp-isa-\d+/Core_\d+"/>
 </display>
 <display hScale="6" column="1" row="2" showUnit="0" manualRange="0" vDistance="30" title="Hard Disk Totals" rowSpan="1" svgBackground="" version="1" hLines="1" columnSpan="1" unit="" fontSize="8" class="FancyPlotter" labels="1" stacked="0" vLines="1" autoRange="1" vScroll="1">
  <beam sensorType="float" summationName="Reads" regexpSensorName="disk/(nvme(\d+|\d+n\d+)|sd[a-z]+|mmcblk\d+)_.*/Rate/rblk" hostName="localhost" color="0xff0057ae"/>
  <beam sensorType="float" summationName="Writes" regexpSensorName="disk/(nvme(\d+|\d+n\d+)|sd[a-z]+|mmcblk\d+)_.*/Rate/wblk" hostName="localhost" color="0xffe20800"/>
 </display>
</WorkSheet>

EOT'
